version: '2'
services:
  example_project-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/Example_Project/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Example_Project
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
